eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceurl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: AddressService
              uri: lb://AddressService
              predicates:
                - Path=/address/**
              filters:
                - AuthFilter
                - name: CircuitBreaker
                  args:
                   name: AddressService
                   fallbackUri: forward:/AddressServiceFallback

            - id: AUTHSERVICE
              uri: lb://AUTHSERVICE
              predicates:
                - Path=/auth/**

            - id: EmployeeService
              uri: lb://EmployeeService
              predicates:
                - Path=/employees/**
              filters:
                - AuthFilter
                - name: CircuitBreaker
                  args:
                    name: EmployeeService
                    fallbackUri: forward:/employeeServiceFallback

resilience4j:
  timelimiter:
    instances:
      EmployeeService:
        timeoutDuration: 5s
      AddressService:
        timeoutDuration: 5s
  circuitbreaker:
    instances:
      EmployeeService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

      AddressService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always